--- #YAML:1.0
name:               CiviCRM-Client-REST
version:            0.01
abstract:           Client library for the CiviCRM REST API
author:
    - Wes Morgan <wmorgan@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:            0
    JSON:            0
    LWP::UserAgent:  0
    perl:            5.006000
    Test::More:      0
    URI::Escape:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
